image: sikalabs/ci

stages:
    - build

variables:
    IMAGE_DEV: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    IMAGE_PROD: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID

build:
    stage: build
    script:
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker build -t $IMAGE_DEV -t $IMAGE_PROD .
        - docker push $IMAGE_DEV
        - docker push $IMAGE_PROD
